/** URL builders — the only place where route strings are spelled out. See docs/02-architecture/routing.md. */
export const paths = {
  home: () => '/',
  path: () => '/path',
  module: (moduleId: string) => `/module/${moduleId}`,
  lesson: (lessonId: string) => `/lesson/${lessonId}`,
  lessonQuiz: (lessonId: string) => `/lesson/${lessonId}/quiz`,
  exam: (moduleId: string) => `/exam/${moduleId}`,
  finalExam: () => '/exam/final',
  simulator: (scenarioId?: string) => (scenarioId ? `/simulator/${scenarioId}` : '/simulator'),
  tools: (calcId?: string) => (calcId ? `/tools/${calcId}` : '/tools'),
  journal: () => '/journal',
  journalNew: () => '/journal/new',
  journalEntry: (id: number | string) => `/journal/${id}`,
  glossary: (termId?: string) => (termId ? `/glossary/${termId}` : '/glossary'),
  cheatsheets: () => '/cheatsheets',
  stats: () => '/stats',
  achievements: () => '/achievements',
  settings: () => '/settings',
  certificate: () => '/certificate',
  plan: () => '/plan',
  about: () => '/about',
  devUi: () => '/dev/ui',
} as const;
